dprojx/dprojx/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

dprojx/event_registration/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# media
from django.conf.urls.static import static
from django.conf import settings
from events import views as event_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^events/', include('events.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^about/$', views.about),
    # url(r'^$', views.homepage),
    url(r'^$', event_views.event_list, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dprojx/events/urls.py
from django.conf.urls import url
from . import views

app_name = 'events'

urlpatterns = [
    url(r'^$', views.event_list, name="list"),

    url(r'^create/$', views.event_create, name="create"),
    url(r'(?P<slug_register>[\w-]+)/register$', views.event_register, name="register"),
#          (?P<slug_register>[\w-]+)/register$

    url(r'(?P<slug>[\w-]+)/$', views.event_detail, name="detail"),

]

dprojx/urls.py
# dprojx/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from dappx import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^dappx/',include('dappx.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

dprojx/events/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Event(models.Model):
    title = models.CharField(max_length=144)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    # thumbnail of event
    thumb = models.ImageField(default="default.png", blank=True)
    # event created by
    author = models.ForeignKey(User, default=None, on_delete=models.DO_NOTHING)
    registered_people = models.CharField(max_length=5000, blank=True, default="")

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + "..."

dprojx/events/forms.py
from django import forms
from . import models


class CreateEvent(forms.ModelForm):
    class Meta:
        model = models.Event
        fields = ['title', 'body', 'slug', 'thumb']


# class Register(forms.ModelForm):
#     class Meta:
#         model = models.Event
#         fields = ['registered_people']

dprojx/events/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from .models import Event
# from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms


# Create your views here.
def event_list(request):
    events = Event.objects.all().order_by('date')
    return render(request, "events/event_list.html", {'events': events})


def event_detail(request, slug):
    # return HttpResponse(slug)
    event = Event.objects.get(slug=slug)
    if event.registered_people:
        event.registered_people = event.registered_people.split(' ')
    return render(request, 'events/event_detail.html', {'event': event})


@login_required(login_url="/accounts/login/")
def event_create(request):
    if request.method == 'POST':
        form = forms.CreateEvent(request.POST, request.FILES)
        if form.is_valid():
            # save to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('events:list')

    else:
        form = forms.CreateEvent()
    return render(request, 'events/event_create.html', {'form': form})


@login_required(login_url="/accounts/login/")
def event_register(request, slug_register):
    print("here")
    event = Event.objects.get(slug=slug_register)
    #    print(type(event.registered_people)_
    search = str(request.user)+" "
    if search not in event.registered_people:
        event.registered_people = str(event.registered_people) + str(request.user) + " "
        event.save()
    else:
        # print to manage.py shell
        print("you're already registered!")
    #    return redirect('events:detail')
    #    return render(request, 'events/event_detail.html', {'event': event})
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

dprojx/events/templates/events/event_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-event">
        <h2>Create a new event</h2>
        <form action="{% url 'events:create' %}" class="site-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Create">
        </form>

    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

dprojx/events/templates/events/event_detail.html
{% extends 'base_layout.html' %}

{% block content%}
<div class="event-detail">
    <div class="event">
        <img src="{{ event.thumb.url }}" alt="">
        <h2>{{event.title}}</h2>
        <p>{{event.body}}</p>
        <p>{{event.date}}</p>


        <a href="{% url 'events:register' slug_register=event.slug %}" class="register">Register <i class="fas fa-user-plus"></i></a>


        <p>Registered people:</p>
        {% for people in event.registered_people %}
        <p>{{people}}</p>
        {% endfor %}
    </div>
</div>

{% endblock %}

dprojx/events/templates/events/event_list.html
{% extends 'base_layout.html' %}

{%block content%}
    <h1>Event List</h1>
    <div class="events">
        {% for event in events %}
        <div class="event">
            <h2><a href="{% url 'events:detail' slug=event.slug %}">{{event.title}}</a></h2>
            <p>{{event.snippet}}</p>
            <p class="author">added by {{event.author.username}}</p>


            <a href="{% url 'events:register' slug_register=event.slug %}">Register <i class="fas fa-user-plus"></i></a>



            <br>
            <br>
            <small>{{event.date}}</small>

        </div>
        {% endfor %}
    </div>
{% endblock %}