dprojx/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

dprojx/dprojx/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

dprojx/event_registration/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# media
from django.conf.urls.static import static
from django.conf import settings
from events import views as event_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^events/', include('events.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^about/$', views.about),
    # url(r'^$', views.homepage),
    url(r'^$', event_views.event_list, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dprojx/events/urls.py
from django.conf.urls import url
from . import views

app_name = 'events'

urlpatterns = [
    url(r'^$', views.event_list, name="list"),

    url(r'^create/$', views.event_create, name="create"),
    url(r'(?P<slug_register>[\w-]+)/register$', views.event_register, name="register"),
#          (?P<slug_register>[\w-]+)/register$

    url(r'(?P<slug>[\w-]+)/$', views.event_detail, name="detail"),

]

dprojx/urls.py
# dprojx/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from dappx import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^dappx/',include('dappx.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

dprojx/templates/about.html
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>About</title>
</head>
<body>

    <h1>About us</h1>
    <p>We like django!</p>
    <p>We like handling events!</p>

</body>
</html>

dprojx/templates/base_layout.html
{% load static from staticfiles %}

<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Events</title>

    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fa-solid.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
</head>
<body>
    <header class="wrapper">
        <h1><a href="{% url 'home' %}" class="font-cursive">
            <!-- <img src="{% static 'logo.png' %}" alt="logo"> -->
            Event Registration
        </a></h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
                <li><a href="{% url 'events:create' %}" class="highlight">New Event</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <div class="wrapper">

        {% block content %}
        {% endblock %}

    </div>
</body>
</html>

dprojx/templates/homepage.html
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Homepage</title>
</head>
<body>
    <h1>This is the homepage</h1>
    <p>Welcome to Event registration</p>
</body>
</html>